import Head from "next/head";
import CarouselComponent from "./components/carousel";

export default function Home() {
    return (
        <>
            <Head>
                <title>Jobs</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/lista.png" />
            </Head>
            <main>
                <CarouselComponent></CarouselComponent>
            </main>
        </>
    );
}
